### ISSUE TITLE
Unexpected subscribe request answer: update

### ISSUE THREAD

**Issue by CitrusVento** [JKorf/FTX.Net#8]
After call SubscribeToTickerUpdatesAsync I get error in CallResult. I think the return types "update" and "partial" needs to be handled. But I don’t understand if the subscription is executed in this case. This situation occurs when a serial subscription for a large number of markets

**Comment by JKorf** [comment]
This should be resolved in the latest update

**Comment by JINK666** [comment]
Hi I still get the error "Unexpected subscribe request answer: update" when calling SubscribeToTickerUpdatesAsync.  I included the code because maybe I am doing something wrong. The error is not thrown all the time, only occasionally. 

Context.extendedSymbols.ForEach(async extended =>
            {
              
                var result = await Context.FTXsocketClient.SubscribeToTickerUpdatesAsync(extended.symbolName, data =>
                {
                    var result2 = data.Data.LastTrade;                 
                 
                });

            });
